"""Simulator-neutral building blocks for a masked joint RL policy."""

from .contracts import (
    ActivationIntent,
    ActivationReceipt,
    BinaryChoice,
    BranchActivity,
    JointAction,
    JointSpaceSpec,
    Movement,
    MovementIntent,
    NO_OBJECTIVE,
    ResolvedIntents,
    RetargetIntent,
    SharedSensorAction,
    SharedSensorConfig,
    SharedSensorIntent,
    SharedSensorReceipt,
    SharedSensorState,
    UnitAction,
    UnitControlState,
    UnitPhase,
)
from .masking import (
    ActionValidationError,
    JointActionMask,
    UnitActionMask,
    branch_activity,
    build_joint_action_mask,
    canonicalize_joint_action,
    expected_log_prob_terms,
    validate_action_against_mask,
    validate_joint_action,
)
from .observation import (
    JointObservationEncoder,
    MapBounds,
    ObjectiveFrame,
    ObservationEncoderConfig,
    UnitFrame,
)
from .state import JointControlTracker
from .slots import ExternalId, StableSlotRegistry
from .trajectory import (
    JointPolicyTrace,
    JointTrajectoryBuffer,
    JointTransition,
    SharedSensorPolicyTrace,
)

__all__ = [
    "ActionValidationError",
    "ActivationIntent",
    "ActivationReceipt",
    "BinaryChoice",
    "BranchActivity",
    "JointAction",
    "JointActionMask",
    "JointSpaceSpec",
    "JointControlTracker",
    "JointObservationEncoder",
    "JointPolicyTrace",
    "JointTrajectoryBuffer",
    "JointTransition",
    "MapBounds",
    "Movement",
    "MovementIntent",
    "NO_OBJECTIVE",
    "ObjectiveFrame",
    "ObservationEncoderConfig",
    "ResolvedIntents",
    "RetargetIntent",
    "SharedSensorAction",
    "SharedSensorConfig",
    "SharedSensorIntent",
    "SharedSensorPolicyTrace",
    "SharedSensorReceipt",
    "SharedSensorState",
    "StableSlotRegistry",
    "UnitAction",
    "UnitActionMask",
    "UnitControlState",
    "UnitFrame",
    "UnitPhase",
    "ExternalId",
    "branch_activity",
    "build_joint_action_mask",
    "canonicalize_joint_action",
    "expected_log_prob_terms",
    "validate_action_against_mask",
    "validate_joint_action",
]
